[package]
name = "bnv"
version = "0.1.0"
edition = "2024"
description = "A beautiful, modern environment variable explorer"
readme = "README.md"
homepage = "https://github.com/slimreaper35/bnv"
repository = "https://github.com/slimreaper35/bnv"
license = "MIT"
keywords = ["cli", "env", "environment"]
categories = ["command-line-utilities"]
exclude = ["assets"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
owo-colors = { version = "4.3.0", features = ["supports-colors"] }
regex = "1.13.0"
